// Mocks generated by Mockito 5.4.6 from annotations
// in lexilingo_app/test/features/progress/data/repositories/progress_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lexilingo_app/features/progress/data/datasources/progress_remote_datasource.dart'
    as _i3;
import 'package:lexilingo_app/features/progress/data/models/progress_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProgressStatsModel_0 extends _i1.SmartFake
    implements _i2.ProgressStatsModel {
  _FakeProgressStatsModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseProgressWithUnitsModel_1 extends _i1.SmartFake
    implements _i2.CourseProgressWithUnitsModel {
  _FakeCourseProgressWithUnitsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeLessonCompletionResultModel_2 extends _i1.SmartFake
    implements _i2.LessonCompletionResultModel {
  _FakeLessonCompletionResultModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgressRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressRemoteDataSource extends _i1.Mock
    implements _i3.ProgressRemoteDataSource {
  MockProgressRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProgressStatsModel> getMyProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getMyProgress, []),
            returnValue: _i4.Future<_i2.ProgressStatsModel>.value(
              _FakeProgressStatsModel_0(
                this,
                Invocation.method(#getMyProgress, []),
              ),
            ),
          )
          as _i4.Future<_i2.ProgressStatsModel>);

  @override
  _i4.Future<_i2.CourseProgressWithUnitsModel> getCourseProgress(
    String? courseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseProgress, [courseId]),
            returnValue: _i4.Future<_i2.CourseProgressWithUnitsModel>.value(
              _FakeCourseProgressWithUnitsModel_1(
                this,
                Invocation.method(#getCourseProgress, [courseId]),
              ),
            ),
          )
          as _i4.Future<_i2.CourseProgressWithUnitsModel>);

  @override
  _i4.Future<_i2.LessonCompletionResultModel> completeLesson({
    required String? lessonId,
    required double? score,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeLesson, [], {
              #lessonId: lessonId,
              #score: score,
            }),
            returnValue: _i4.Future<_i2.LessonCompletionResultModel>.value(
              _FakeLessonCompletionResultModel_2(
                this,
                Invocation.method(#completeLesson, [], {
                  #lessonId: lessonId,
                  #score: score,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.LessonCompletionResultModel>);

  @override
  _i4.Future<int> getTotalXp() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalXp, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
