#!/bin/bash
# Quick test script for chat response

echo "🧪 Testing Chat Response..."
echo ""
echo "✅ Steps completed:"
echo "  1. Fixed model name: gemini-pro → gemini-1.5-flash"
echo "  2. Added API key instructions"
echo ""
echo "⚠️  TODO: Update API key in injection_container.dart"
echo ""
echo "📝 Next steps:"
echo "  1. Get API key: https://ai.google.dev/"
echo "  2. Open: lib/core/di/injection_container.dart"
echo "  3. Line 149: Replace 'YOUR_API_KEY' with real key"
echo "  4. Run: flutter run"
echo "  5. Test: Send 'hi' in chat"
echo ""
echo "💡 Or use Quick Fix:"
echo "  sed -i '' \"s/'YOUR_API_KEY'/'your_real_key_here'/g\" lib/core/di/injection_container.dart"
