// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxb89kPDmWalE3fx8Jlo45pNYMfpe-Q5I',
    appId: '1:432329288238:web:1e2bb6c5f46c35b2718dbf',
    messagingSenderId: '432329288238',
    projectId: 'lexilingo-88492',
    authDomain: 'lexilingo-88492.firebaseapp.com',
    storageBucket: 'lexilingo-88492.firebasestorage.app',
    measurementId: 'G-H6F7RM710J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:432329288238:android:27021651b0302784718dbf',
    messagingSenderId: '432329288238',
    projectId: 'lexilingo-88492',
    storageBucket: 'lexilingo-88492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnGOEn-S0gI75ZsznWAE8KZslFbXZVhx4',
    appId: '1:432329288238:ios:982737f02386c9ac718dbf',
    messagingSenderId: '432329288238',
    projectId: 'lexilingo-88492',
    storageBucket: 'lexilingo-88492.firebasestorage.app',
    iosBundleId: 'com.lexilingo.lexilingoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnGOEn-S0gI75ZsznWAE8KZslFbXZVhx4',
    appId: '1:432329288238:ios:982737f02386c9ac718dbf',
    messagingSenderId: '432329288238',
    projectId: 'lexilingo-88492',
    storageBucket: 'lexilingo-88492.firebasestorage.app',
    iosBundleId: 'com.lexilingo.lexilingoApp',
  );
}
